### ISSUE TITLE
Peer Review - Incomplete Section (G.4.2)

### ISSUE THREAD

**Issue by 1Midnight1** [takhtart/PCD#9]
**Artifact Under Review**

SRS section **G.4.2**

**Team Number for Team Doing the Review**

Team 13

**Description of Issue**

I assume this section is incomplete as it cuts off mid sentence. It seems to be missing the explanation for why 3D space estimation is important

**Comment by takhtart** [comment]
Thank you for letting me know, seems the file was prematurely committed and missed.
